apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: claudemirpereiralima/backend-feed
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aws-secret-volume
          mountPath: "/root/.aws"
          readOnly: true
        envFrom:
        - configMapRef:
            name: udagram-config
        - secretRef:
            name: udagram-secret
      volumes:
      - name: aws-secret-volume
        secret:
          secretName: aws-secret
