apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: claudemirpereiralima/reverse-proxy
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: udagram-config
        - secretRef:
            name: udagram-secret
        - secretRef:
            name: aws-secret