apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udagram-claudemir-cluster
  region: us-east-1

vpc:
  id: 
  subnets:
    public:
      us-east-1a:
        id: 
      us-east-1b:
        id: 
  securityGroup: 

nodeGroups:
  - name: ng-udagram
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    ssh:
      allow: true
      publicKeyName: 